# room :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

variables:
- group: azure.vars
- group: cloudflare.vars
- group: sonarcloud.vars
- { name: id, value: room }
- { name: directory, value: room }
- { name: sonar.key, value: roomxyz }
- { name: sonar.name, value: ROOM }
- { name: sonar.version, value: '0.0.0' }
- { name: namespace, value: Room }
- { name: terraform, value: .terraformio }
- { name: webapp, value: aspnet }

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/aspnet.yml
    - .azure/stages/deploy.yml
    - room

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/stages/aspnet.yml
    - .azure/stages/deploy.yml
    - room

stages:
- template: ../../.azure/stages/aspnet.yml
  parameters:
    id: $(id)
- template: ../../.azure/stages/deploy.yml
  parameters:
    id: $(id)
