# complex :: docker-compose

networks:
  complex_localhost:
services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: complex
    depends_on:
      - data
    ports:
      - 13080:80
    networks:
      - complex_localhost
    environment:
      ConnectionStrings__ComplexDb: ''
      ConnectionStrings__ServiceBus: ''
  data:
    image: postgres:12.0
    networks:
      - complex_localhost
    environment:
      POSTGRES_PASSWORD: 'Pass@word'
version: '3.7'
