# addressxyz :: docker

## arguments
ARG DOTNET_VERSION=2.2

## stage - restore
FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION} as restore
WORKDIR /aspnet
COPY ./aspnet .
RUN dotnet restore *.sln

## stage - publish
FROM restore as publish
RUN dotnet publish */*.Api.csproj --configuration Release --no-restore --output /aspnet/dist

## stage - deploy
FROM mcr.microsoft.com/dotnet/core/aspnet:${DOTNET_VERSION} as deploy
WORKDIR /api
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
COPY --from=publish /aspnet/dist .
CMD [ "bash", "-c", "dotnet *.Api.dll" ]
