# address :: docker-compose

networks:
  address_localhost:
services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: address
    depends_on:
      - data
    ports:
      - 10080:80
    networks:
      - address_localhost
    environment:
      ConnectionStrings__AddressDb: 'Host=data;Database=address;Username=postgres;Password=Pass@word'
  data:
    image: postgres:12.0
    networks:
      - address_localhost
    environment:
      POSTGRES_PASSWORD: 'Pass@word'
version: '3.7'
