# account :: docker-compose

networks:
  account_localhost:
services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: account
    depends_on:
      - data
    ports:
      - 10080:80
    networks:
      - account_localhost
    deploy:
      replicas: 1
    environment:
      ConnectionStrings__AccountDb: 'Host=data;Database=account;Username=postgres;Password=Pass@word'
  data:
    image: postgres:12.0
    networks:
      - account_localhost
    environment:
      POSTGRES_PASSWORD: 'Pass@word'
version: '3.7'