# tenantxyz :: docker

## arguments
ARG DOTNET_VERSION=3.0

## stage - restore
FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION} as restore
WORKDIR /aspnet
COPY aspnet/Xyz.Tenant.Api/*.csproj Xyz.Provider.Api/
COPY aspnet/Xyz.Tenant.DataAccess/*.csproj Xyz.Provider.DataAccess/
COPY aspnet/Xyz.Tenant.Lib/*.csproj Xyz.Provider.Lib/
RUN dotnet restore *.Api

# ## stage - publish
FROM restore as publish
COPY aspnet/Xyz.Tenant.Api/*.csproj Xyz.Provider.Api/
COPY aspnet/Xyz.Tenant.DataAccess/*.csproj Xyz.Provider.DataAccess/
COPY aspnet/Xyz.Tenant.Lib/*.csproj Xyz.Provider.Lib/
RUN dotnet publish *.Api --configuration Release --no-restore --output /aspnet/dist

## stage - deploy
FROM mcr.microsoft.com/dotnet/core/aspnet:${DOTNET_VERSION} as deploy
WORKDIR /api
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
COPY --from=publish /src/dist/ ./
CMD dotnet *.Api.dll
