# tenant :: docker-compose

networks:
  tenant_localhost:
services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: tenant
    depends_on:
      - data
    ports:
      - 10080:80
    networks:
      - tenant_localhost
    environment:
      ConnectionStrings__TenantDb: 'Host=data;Database=tenant;Username=postgres;Password=Pass@word'
  data:
    image: postgres:12.0
    networks:
      - tenant_localhost
    environment:
      POSTGRES_PASSWORD: 'Pass@word'
version: '3.7'
