# housing :: docker-compose

networks:
  housing_localhost:

services:
  web:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    image: housing
    networks:
      - housing_localhost
    ports:
      - 10080:80
      - 10443:443

version: '3.7'
