# housing :: dockerfile

## arguments
ARG NGINX_VERSION=1.17
ARG NODE_VERSION=12.10

## stage - base
FROM node:${NODE_VERSION} as base
WORKDIR /src
COPY ./src/package*.json ./
RUN npm ci

## stage - build
FROM base as build
COPY ./src .
RUN npm run build

## stage - deploy
FROM nginx:${NGINX_VERSION} as deploy
COPY ./.docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/dist/housing /usr/share/nginx/html
