// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Xyz.Address.Dbx;

namespace Xyz.Address.Dbx.Migrations
{
    [DbContext(typeof(AddressDbContext))]
    [Migration("20190930194250_address_db_entity")]
    partial class address_db_entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Xyz.Address.Dbx.Models.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("City")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnName("Country")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateModified");

                    b.Property<Guid>("Key")
                        .HasColumnName("Key");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnName("PostalCode")
                        .HasColumnType("varchar")
                        .HasMaxLength(5);

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasColumnName("StateProvince")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnName("Street")
                        .HasColumnType("varchar")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
