# housingxyz :: dockerfile

## arguments
ARG NGINX_VERSION=1.17
ARG NODE_VERSION=12.5

## stage - base
FROM node:${NODE_VERSION} as base
WORKDIR /housingxyz
COPY package*.json .
RUN npm clean-install

## stage - build
FROM base as build
COPY . .

## stage - deploy
FROM nginx:${NGINX_VERSION} as deploy
COPY --from=build /housingxyz/dist /usr/share/nginx/html
