# housingxyz :: dockerfile

## arguments
ARG NGINX_VERSION=1.17
ARG NODE_VERSION=12.5

## stage - base
FROM node:${NODE_VERSION} as base
WORKDIR /angular
COPY ./angular/package*.json ./
RUN npm clean-install

## stage - build
FROM base as build
COPY ./angular .
COPY --from=base ./angular .
RUN npm run build:ci

## stage - deploy
FROM nginx:${NGINX_VERSION} as deploy
COPY ./.docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /angular/dist/housingxyz /usr/share/nginx/html
