# tenant :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

variables:
- group: azure.vars
- group: cloudflare.vars
- group: sonarcloud.vars
- { name: directory, value: tenant }
- { name: sonar.key, value: tenantxyz }
- { name: sonar.name, value: TENANT }
- { name: sonar.version, value: '0.0.0' }
- { name: namespace, value: Tenant }
- { name: terraform, value: .terraformio }
- { name: webapp, value: aspnet }

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure
    - tenant

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure
    - tenant

stages:
- template: ../../.azure/stages/aspnet.yml
  parameters:
    id: $(id)
- template: ../../.azure/stages/deploy.yml
  parameters:
    id: $(id)
