# providerxyz :: docker

## arguments
ARG DOTNET_VERSION=3.0

## stage - restore
FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION} as restore
WORKDIR /aspnet
COPY aspnet/Xyz.Provider.Api/*.csproj Xyz.Provider.Api/
COPY aspnet/Xyz.Provider.DataAccess/*.csproj Xyz.Provider.DataAccess/
COPY aspnet/Xyz.Provider.Lib/*.csproj Xyz.Provider.Lib/
RUN dotnet restore *.Api

## stage - publish
FROM restore as publish
COPY aspnet/Xyz.Provider.Api/ Xyz.Provider.Api/
COPY aspnet/Xyz.Provider.DataAccess/ Xyz.Provider.DataAccess/
COPY aspnet/Xyz.Provider.Lib/ Xyz.Provider.Lib/
RUN dotnet publish *.Api --configuration Release --no-restore --output /aspnet/dist

## stage - deploy
FROM mcr.microsoft.com/dotnet/core/aspnet:${DOTNET_VERSION} as deploy
WORKDIR /api
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
HEALTHCHECK --timeout=5s CMD curl --fail http://localhost/health || exit
COPY --from=publish /aspnet/dist/ ./
CMD dotnet *.Api.dll
